### ISSUE TITLE
Germplasm Collections filter on germplasm search

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/kp_searches#5]
There is a need to provide a filter for chado.stock_collection to allow users to search for germplasm collections such as diversity panels.

**Comment by laceysanderson** [comment]
Also add a germplasm collection field so that germplasm will say they are part of a collection and so projects can say they use a collection.

**Comment by reynoldtan** [comment]
![image](https://user-images.githubusercontent.com/15472253/184173831-7fe7ee49-1a8f-4e87-8d6b-3b6b3211eab5.png)
